package com.myspace.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DataObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.myspace.test.NestedObject> multipleSubform;

	public DataObject() {
	}

	public java.util.List<com.myspace.test.NestedObject> getMultipleSubform() {
		return this.multipleSubform;
	}

	public void setMultipleSubform(
			java.util.List<com.myspace.test.NestedObject> multipleSubform) {
		this.multipleSubform = multipleSubform;
	}

	public DataObject(
			java.util.List<com.myspace.test.NestedObject> multipleSubform) {
		this.multipleSubform = multipleSubform;
	}

}