package com.myspace.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NestedObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public NestedObject() {
    }




}