package com.myspace.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NestedObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int age;

	public NestedObject() {
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public NestedObject(int age) {
		this.age = age;
	}

}